version: "3.7"
services:
# 此处mysql与smproxy不能搭配使用，因为mysql启动较慢，可在smproxy的dockerfile里面编写监测，再启动
#  mysql:
#    image: mysql:5.7.18
#    ports:
#      - "3307:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#    volumes:
#      - ./mysql:/var/lib/mysql
#      - ./mysql-config:/etc/mysql/conf.d

  php-7.1-fpm:
    image: bitnami/php-fpm:latest
    ports:
      - "9011:9000"
    volumes:
      - ./www:/var/www/html
  nginx:
      image: nginx:latest
      command: nginx -g 'daemon off;'
      volumes:
        - ./www:/var/www/html:ro
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
      ports:
        - "80:80"
      links:
      #  - php-5.6-fpm
        - php-7.1-fpm
  smproxy:
    build: ./SMProxy
    volumes:
        - ./proxy/conf:/usr/local/smproxy/conf
        - ./proxy/logs:/usr/local/smproxy/logs
    ports:
      - "3309:3306"
#    depends_on:
#      - mysql